### ISSUE TITLE
Suggestion: a time-based instead of word-based caption buffer

### ISSUE THREAD

**Issue by casperdewith** [greenwyrt/plover2CAT#18]
Currently, when setting up live captioning (_Audiovisual > Captioning_), the dialog box asks you to enter a buffer size, which is counted in words.

![The ‘Captioning Settings’ dialog box, where the ‘Word buffer’ field has value 5.](https://github.com/user-attachments/assets/ae6473d6-2071-4f23-ad3d-50c4562183f9)

I would like to be able to choose a different unit: a (real) number of seconds. This means that when this unit is selected, and I chose _x_ seconds, any prefix of my buffer that has not changed for more than _x_ seconds is output.

I request this functionality because some strokes in my steno theory have a lot of words. I obviously want to be able to undo any single stroke without anyone noticing, so I have to use a large buffer. As a consequence, though, the delay between me stroking a stroke and it being displayed is often long. And manually flushing the buffer after every sentence to shorten this delay is not fun.

**Comment by greenwyrt** [comment]
I can definitely see the usefulness of this feature. The places that have to be changed are the `display_captions` in the window editor and `send_cap` in captionWorker. It probably will take me a bit of time to work on this, because the buffer mechanism right now is based solely on the text, and using the time is something different. 

I have an idea of an approach and this is more a comment to myself: to start, in [display_captions](https://github.com/greenwyrt/plover2CAT/blob/main/plover_cat/PloverCATWindow.py#L2656), subset paragraph element collection by last pos to word before cursor, do time diff, use length of elements that pass to move cursor to new position.
